# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f1b5396bafc4dbb32239ca1256d6c78874533da1189185b121ac88b6622090ba96a596deacaf2a38d6fc908dc6cb08808266726cdd3fc513df80ecd0c4ce267

test:
  secret_key_base: c76b0772877b4cf35f129d7bd928501f6d8bb9b5ef85eba3eaa5f3e16e3cd5258f52808f53890326b33f0d3870c696ae01705a23d4d2dc3a30f7f6e26a6b7c5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
